version: "3"
services:
    frontend:
        container_name: OnlineStudyPortal_Web
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/usr/src/app
    backend:
        container_name: OnlineStudyPortal_API
        build:
            context: ./OnlineStudyPortal
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ./OnlineStudyPortal:/usr/src/app